<?php

/**
 * @param $url
 * @param $referer
 * @param $isDownload
 * @param $localFd
 * @param $isPost
 * @param $isJson
 * @param $data
 * @return bool|string
 */
function curl($url, $referer = "https://madou.club/", $isDownload = 0, $localFd = null, $isPost = 0, $isJson = 0, $data = [])
{
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, !$isDownload);
    if ($isDownload) {
        curl_setopt($ch, CURLOPT_FILE, $localFd);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
        curl_setopt($ch, CURLOPT_TIMEOUT, 200000);
    }
    curl_setopt($ch, CURLOPT_VERBOSE, false);
    curl_setopt($ch, CURLOPT_HEADERFUNCTION, function ($a, $b) {
//        var_dump($a);
//        var_dump($b);
        return strlen($b);
    });
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_POST, $isPost);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, $isPost ? "POST" : "GET");
    curl_setopt($ch, CURLOPT_POSTFIELDS, $isJson ? json_encode($data) : http_build_query($data));

    $headers = array();
    $headers[] = $isJson ? "Content-Type: application/json" : "Content-Type: text/html";
    $headers[] = "User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4243.0 Safari/537.36";
    $headers[] = "Upgrade-Insecure-Requests: 1";
    $headers[] = sprintf("Referer: %s", $referer);
    $headers[] = sprintf("Origin: %s", $referer);
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        var_dump(curl_getinfo($ch));
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
    return $result;
}